### ISSUE TITLE
Suggest new entries for funfacts

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#2] opened 2018-08-20 00:24 UTC
Opened this issue so that everyone can post suggestions for new retrogaming funfacts.

The current ones are here: https://github.com/RetroAchievements/RABot/blob/master/assets/json/funfacts.json

Just post your suggestions here and I'll add them to the list ASAP.

**Comment by meleu** [comment] 2018-08-20 17:19
I've found some funfacts here: https://www.reddit.com/r/retrogaming/comments/1l4acw/10_interesting_retro_gaming_facts/

Not sure if they are legitimate, though (as everything on the internet :sweat_smile:)

- Die Hard Arcade for the Sega Saturn was originally going to be Streets of Rage 4.

- Gunpei Yokoi (creator of the Game Boy) once worked at Nintendo's headquarters as a janitor.

- There is a fully functional ZX Spectrum emulator in the code of Goldeneye 007.

- Mario composer Koji Kondo once met Paul McCartney. McCartney started singing the Super Mario Bros. theme upon meeting Kondo.

- The fatalities in Mortal Kombat were discovered and first performed by a 12 year old kid.

Nonsense :point_up_2: 

- Quake was in development before Doom.

Someone said that this :point_up_2: is not true:

> Not true. Quake as we know it was developed after Doom. The name Quake was originally the name of the protagonist of an unreleased game, The Fight for Justice, that was suppose to be a 2d side scrolling rpg follow up to the Commander Keen games.


- In Space Invaders, the invaders speeding up as the screen becomes less full was unintentional.

- Apple released a console called the Apple Bandai Pippin in 1995, it failed miserably.

- Sonic can't swim because the employees at Sega believed that Hedgehogs couldn't swim.

- The arcade game Tempest was reported to have caused nausea and epileptic seizures to its players when it was first released leading to the recall of all arcade cabinets containing the early build of the game. Many reports of the story were exaggerated and taken out of context which in turn gave birth to the infamous Polybius urban legend.

**Comment by rabbids4eva** [comment] 2018-08-27 22:08
Quest 64 is called "Holy Magic Century" in Europe and "Eltale Monsters" in Japan.
https://www.vgfacts.com/game/quest64/#trivia

The Atari 2600 was the first video game console to have wireless controllers. The Atari CX-42 joystick controllers used radio waves to transmit information, and they released in 1983.

The CVC GameLine cartridge made it possible to download games via phoneline for the Atari 2600 in 1983, over 20 years earlier than services like Xbox Live Arcade.

Due to South Korea banning Japanese cultural imports at the end of World War II, the Game Gear was distributed by South Korean company Samsung, and was named the Handy Gam*Boy.

The Genesis was the first SEGA console to have online play, but it was only compatible with a handful of games and the lifespan for the modem device was less than one year.

Since the Super Nintendo wasn't powerful enough to emulate a GameBoy with software, the Super GameBoy actually contained all the hardware of a regular GameBoy except for the screen and buttons.

In Japan, Nintendo decided to ship the Super Famicom at night to avoid being robbed by the Yazuka.

Clive Sinclair was knighted in 1983 for the creation of the ZX Spectrum and how its significance greatly contributed to the British industry.

**Comment by rabbids4eva** [comment] 2018-09-03 23:09
In LEGO Worlds, the spaceship you use to travel worlds is named Pug-Z, which is a nod to Puggsy, one of the early games from LEGO World's developer, Traveller's Tales.

**Comment by rabbids4eva** [comment] 2018-09-03 23:13
Conker's Bad Fur Day was originally going to be Twelve Tales: Conker 64, but due to a lot of people making fun of Rare for making too many kid-friendly platformers, Rare re-worked it into the M-rated comedy platformer, with Conker becoming an alcoholic, foul-mouthed squirrel we know and love today.

**Comment by rabbids4eva** [comment] 2018-09-03 23:14
Mary Kate & Ashley Get a Clue was originally meant to be a South Park game.

**Comment by meleu** [comment] 2018-09-04 01:00
hey @rabbids4eva would you mind to put the name of the console between parentheses? Example: Conker's Bad Fur Day (N64).

**Comment by coolscribble** [comment] 2018-09-25 19:03
The infamous “Turbo Tunnel” speeder bike stage from Battletoads (NES) is actually one of the easiest in the game. The Turbo Tunnel is actually one of the least challenging levels in Battletoads. In fact, there are three other racing-style levels in the game — Surf City, Volkmire’s Inferno and Clinger Winger — and they’re all significantly harder than the Turbo Tunnel.

**Comment by coolscribble** [comment] 2018-09-25 19:06
Zelda (Legend of Zelda: NES) was named after Zelda Fitzgerald, wife of “Great Gatsby” author F. Scott Fitzgerald. Miyamoto says he wanted the game’s princess to have a mysterious quality and Mrs. Fitzgerald fit the bill perfectly.

**Comment by coolscribble** [comment] 2018-09-25 19:08
Link (Legend of Zelda: NES) is left-handed in every game until the Wii versions were released that featured a right-handed Link to accommodate the right-handed noobs and their Wiimotes.

**Comment by coolscribble** [comment] 2018-09-25 19:11
The Dracula-based video game Castlevania (NES) is particularly valuable these days. Sealed versions of the game sell for upwards of $900, depending on the condition. Original Nintendo NES editions of Castlevania and Castlevania 2 have sold for more than $950.

**Comment by coolscribble** [comment] 2018-09-25 19:11
Ice Climber(NES) was the first game that Kazuaki Morita worked on. He would go on to refine the game's formula for his next title at Nintendo: Super Mario Bros.(NES), where the action moved horizontally instead of vertically.

**Comment by coolscribble** [comment] 2018-09-25 19:13
The end of Double Dragon II: The Revenge differs on both the NES and arcade. SPOILER: On the NES, damsel-in-distress Marian is brought back to life after being killed early in the story; the arcade version ends on a much more dour note, leaving her dead.

**Comment by coolscribble** [comment] 2018-09-25 19:15
Ninja Gaiden's (NES) director, Hideo Yoshizawa (credited as Sakurazaki), wanted the NES version of the game to have a much deeper story than the arcade version, so he implemented 20 minutes of cinematic cutscenes. Though standard now, a story told through cutscenes was revolutionary at the time.

**Comment by coolscribble** [comment] 2018-09-25 19:29
When Yoshi’s Island’s producer—and Mario creator—Shigeru Miyamoto unveiled the game to the company, his brightly colored, cartoony graphics were rejected by the marketing department. They wanted something more akin to what developer Rare did with Donkey Kong, not the type of visuals that Miyamoto was going for. Miyamoto doubled-down on his vision, retooling Yoshi’s Island’s visuals to become even more colorful and exaggerated, almost like illustrations you would find in a storybook. Oddly enough, this second pitch was accepted, leading to one of the console’s most successful games, topping out at around 4 million units sold.

**Comment by Blazekickn** [comment] 2018-09-25 19:46
Rhydon was the first Pokémon to ever be created, having an ID of 01 if you look into the code of Pokémon Red & Blue. Kangaskhan was the second.

**Comment by meleu** [comment] 2018-09-25 19:47
There's a scene on the Super Mario Bros. film (1993) where the characters says their last name is Mario, therefore fullnames are Mario Mario and Luigi Mario (the Mario Bros.). But in an interview to gameinformer Shigeru Miyamoto said "Mario is really just Mario and Luigi is really just Luigi".
Source: <https://www.gameinformer.com/b/features/archive/2015/09/10/miyamoto-tezuka-interview.aspx>
Movie scene: <https://youtu.be/7MNEF7kjf9s>

**Comment by Blazekickn** [comment] 2018-09-25 19:55
Unfinished entries for plenty of Johto Pokémon can be found in the code of Pokémon Red & Blue, implying that they were originally going to be introduced earlier. These include (in order) Scizor, Shuckle, Heracross, Ho-oh, Sneasel, the Teddiursa line, the Slugma line, the Swinub line, Corsola, the Remoraid line, Delibird, Mantine, Skarmory, the Houndour line, Kingdra, the Phanpy line, Porygon2, Stantler, Smeargle, Tyrogue and Hitmontop, Smoochum, Elekid, Magby, Miltank, Blissey, The Legendary Dogs, the Larvitar line, and Lugia.

**Comment by Blazekickn** [comment] 2018-09-25 19:59
Unused cries that sound similar to that of Shellos and Gastrodon of the Generation 4 Pokémon games can be found in the Sound Test in Pokémon Ruby & Sapphire (accessable through hacking). Unused sprites for them also exist in the game's data, and reflect a hybrid of sorts of the final's East and West forms.

**Comment by rabbids4eva** [comment] 2018-09-26 17:40
Worms (1995) was originally called "Total Wormage!", a play on a Midway arcade game Total Carnage.

Source: https://www.youtube.com/watch?v=08C-ttHHKFs

**Comment by coolscribble** [comment] 2018-09-27 09:57
When Nintendo Game Boy was released its most popular game was Super Mario Land. (RA has set with it)

**Comment by coolscribble** [comment] 2018-09-27 09:58
Game Boy was originally designed to be of major interest to female video game players. By 1995 it had a female audience of 46%.

**Comment by coolscribble** [comment] 2018-09-27 09:58
The selfie was basically invented through the Game Boy. A Game Boy digital camera with a thermal printer was released in 1998, making it possible for players to take pictures of themselves and print them.

**Comment by coolscribble** [comment] 2018-09-27 09:59
Game Boy was released only four years after the launch of Nintendo Entertainment System, introduced in 1985, eventually bringing hits like Mario and Zelda into homes for the first time.

**Comment by coolscribble** [comment] 2018-09-27 10:01
The price of first GameBoy was only $89.99

**Comment by coolscribble** [comment] 2018-09-27 10:03
Nintendo says on its website that Game Boy is the "most successful video game system ever released, but Game Boy sold over 118 million units and Nintendo DS sold over 150 million units.

**Comment by coolscribble** [comment] 2018-09-27 10:04
Nintendo reached older audience by dropping the "boy" element in Nintendo DS, according to US Gamer.

**Comment by coolscribble** [comment] 2018-09-27 10:07
The cover of the Neil Young album "Silver and Gold" was taken with a Game Boy Camera.

**Comment by CoolCanuck** [comment] 2018-10-14 22:44
The startup screen on PlayStation 2 shows different amount of towers based on how many games you played, and the height of the towers shows how long you played a game. (Based on memory card)

The SEGA Saturn was the first gaming console to ship with internal memory. Players could save about 5–6 games on the system’s RAM... all 32 kilobytes of it.


Steve Wozniak’s (apple co-founder) favorite game was Tetris. So much that, in 1900s, he submitted his high scores to Nintendo Power so many times that they refused to print his scores. So he started sending them under another name, “Evets Kainzow” that is reversed of his name.

Xbox was originally named as DirectX Box as a reference to Microsoft’s graphics API, DirectX.

In 2005, a glitch in World of Warcraft allowed a plague to spread in the game leading non-infected players to abandon cities while those infected were forced into quarantines. It was later studied by epidemiologists to see how real life people would react to a pandemic.

The creators of Pac-Man did not know how the game ended as it was designed to run indefinitely. It was only when Billy Mitchell finished the game, after all its internal storage ran out, that they saw how it ended.

The Japanese version of Fallout 3 does not give the player the option to detonate the Megaton nuclear bomb.

**Comment by ViperZang** [comment] 2018-10-14 23:44
Kazumi Totaka includes a 19 note melody in every game where he is credited in a music-related role. "Totaka's Song" was first discovered in Mario Paint (SNES), but it's first appearance in X (GB) wasn't discovered until 15 years after it's 1992 release. It has yet to be found in Wave Race 64 (N64), Wii Sports (Wii), Wii Music (Wii), and Healthy Recipe Assistant 1000: DS Menu Anthology (NDS).

**Comment by rabbids4eva** [comment] 2018-10-15 00:00
D2 was originally planned for the 3DO successor, Panasonic M2. But when the console was cancelled, WARP Inc reworked the game for the SEGA Dreamcast.

Kenji Eno, the founder of WARP and the creator of D, was so angry with Sony for not meeting the pre-order demands for the PS1 port of D he announced at the Sony conference that his next game, Enemy Zero, would become a SEGA Saturn exclusive.

When D was originally released for the 3DO in Japan, Kenji Eno had a little problem getting the game to the US because of the violence and cannibalism seen in the game. His workaround was that he would make a "clean" version of the game so he could get the game approved by the rating board and censors, earning it a Teen rating from the ESRB. On the way to the production plant to make the game copies, he switched the "clean" version with the version he intended to use, thus he put a loophole to his advantage.

D2 Shock demo has a special save that unlocks a secret movie in the full version of the Japanese release, accessible in the main menu. The "secret movie" was actually footage of the scrapped M2 version of D2. That clip can also seen in during the opening scene as an in-flight movie.

In the cancelled M2 version of D2, players would have taken the role of Laura's son in the medieval times.

Although D, D2 and Enemy Zero are unrelated to each other story-wise, they share one noticable thing: the main character, Laura, appears in all three games, just with different surnames. Kenji Eno described Laura as a "digital actress."

Driv3r was infamous for the "Driv3rgate" scandal, where Infogrames (AKA Atari SA) gave PSM2 and Xbox World exclusivity and early access in exchange for stellar reviews. PSM2 and Xbox World both gave it 9/10's while other publications gave it more realistic 3/10's or 4/10's.

Skweek for the Amstrad CPC was recalled because it was discovered that every time you finish the level, Skweek would tell the player to f*** their mother.

The Lion King was insanely hard because Disney didn't want people to rent the game than actually buy it upfront, so Westwood, the developer, made it super hard.

The bad quality of Fantasia for the Genesis and its following recall and controversy surrounding the fact that SEGA didn't get permission to make a game based on the film (yet Infogrames made the game anyway) was often presumed to be the main reason why Disney founded the now-defunct Disney Interactive in the first place.

There was originally an improved PS1 version of the infamous Superman 64, but it was cancelled because Titus realised they spent such a long time making the game, their license with DC Comics and Warner Bros. expired.

**Comment by rabbids4eva** [comment] 2018-10-17 18:59
Despite being cancelled by the now-despised EA, Thrill Kill was the first game to get an Adults Only rating from the ESRB.

After Thrill Kill's cancellation, developer Paradox Developments didn't let the engine go to waste by using it for four games: Wu-Tang Shaolin Warriors, X-Men Mutant Academy 1 and 2 and Rock'em Sock'em Robots Arena.

The PS2 game, Ico, was originally meant to be released for the original PlayStation.

**Comment by rabbids4eva** [comment] 2018-10-22 14:54
The sound effects Yoshi makes are noises made by Kasumi Totaka sped up.

Originally a Sega Saturn port of Bubsy 3D was planned to be made, as seen in promotional material from Winter 1996. This version was most likely cancelled because of the poor reception and sales for the game.

There were originally plans for the PS2 version of Activision Anthology to allow you to download additional games from the game's website and play them on your system, but it was never actually implemented. According to the games producer, it was requested by Sony to be removed at the last minute.

Activision was the first third-party developer to receive credit as a third-party, with its first games being released on the Atari 2600. Activision took Atari to court to gain the right to develop for the Atari 2600, and won, paving the way for third-party developers and crediting creators in games. Atari previously didn't allow other companies to make games for their console, and developers received no credit.

Enemy Zero holds a Guinness World Record for 'Most Exclusive Limited Edition', with just 20 copies ever produced. They cost the equivalent of $2000 each and were hand-delivered by Kenji Eno (the game's director) himself.

In 1996, Atari developed a beat em' up arcade game of Beavis and Butthead that never made it past prototyping due to poor testing. The prototype was eventually restored in 2016, and is the only functioning cabinet for the game that exists.

In the American release of "Gex: Enter the Gecko", Gex is voiced by comedian Dana Gould. However in the European release of the game, Gould's voice was replaced by that of English actor Leslie Phillips, who provided a very different, more cultured and refined variation of the character.

Demos of Crash Bash, found on demo discs and Spyro: Year of the Dragon, contain full versions of the game. The rest of the game besides the demo content is simply locked, but can be accessed through the use of a cheat code. There are many differences between the game's demo release and the final retail game.

Hidden in the code for The New Tetris are several rants and pieces of text-art by programmer David Pridie. The rants are mainly about the incompetence of his co-workers, and the text art is of several logos, a Canadian flag, a cannabis leaf, and (possibly) some psychoactive psilocybin mushrooms.

Originally Frogger 2: Swampy's Revenge was planned to have a Nintendo 64 release, similar to Glover, however this version was cancelled for unknown reasons and all that remains is a largely unfinished prototype version.

With Hasbro Interactive at one point acquiring multiple studios and making increasing profits in game sales, Hasbro Interactive's former president, Tom Dusenberry, had aspirations of one day acquiring Electronic Arts. Sadly, it never happened.

Hudson's mascot Hu-Bee is a reference to the Hudson Hornet, a 1950's sedan built by the Hudson Automobile Company. The two companies are unrelated.

The Greatest Hits version of Spyro: Year of The Dragon has many different changes to the music in the game, with many new tracks being added to areas that previously reused tracks meant for another portion of the game. In some cases, the correct track was already present, but went unused until the Greatest Hits release.

In ClayFighter 63 1/3, There was originally going to be one more character which went by the name 'Hobo Cop' (a pun on the movie RoboCop) who was decorated with pots and trash can lids. For one reason or another, the character was dropped.

ClayFighter: Sculptor's Cut was originally released as a rental only game to Blockbuster Video stores in North America, with additional copies available through an online contest. Because of this, it is considered the rarest and most expensive N64 retail release. Complete copies of the game can sell for more than $1,000 USD.

The name of the infamous LJN came from the initials of Lewis J. Norman, the reverse of Norman J. Lewis, whose toy company had employed Jack Friedman, LJN's founder, as a sales representative in the 1960s.

When SEGA went bust, Microsoft wanted to buy SEGA to try and make their way into the Video Game Market. The deal never went through. This was because Bill Gates didn't think SEGA had the power to stop Sony, so they decided to try and do it on their own.

Due to space limitations, the N64 version of Mortal Kombat Trilogy does not feature the unmasked MK3 version of Sub-Zero as a playable character. Instead the masked, classic ninja version of the character is altered to use his plot, ending and moveset including Ice Clone and Ice Shower.

Free Radical, now Crytek UK, were originally approached by Activision to develop the GoldenEye 007 remake, mainly due to many of Rare's former staff working there, some of whom had worked on the original GoldenEye. However the deal was never finalized and Free Radical never received a proper explanation from Activision as to why the opportunity disappeared.

McDonald's once sold demo discs of PaRappa the Rapper 2 and Ape Escape 2001 to promote the games in Japan. The PaRappa 2 demo took place in the first level, except with a McDonald's theme.

Sony's decision to bring Vib-Ribbon to the PlayStation Network came as a result of Sony Computer Entertainment of America's President and CEO, Shawn Layden, throwing out the name on-stage at E3 2014, unaware that Vib-Ribbon was never originally released in North America. The outcry from fans to release it in North America following the conference spurred Layden to demand a port of it for American consoles.


Crash Bandicoot was originally going to have traditionally-animated cutscenes, but these cutscenes were never implemented into the game. The reason for the cutscenes being dropped was that Sony wanted to emphasize the 3D graphics in the game.
Source: https://www.youtube.com/watch?v=1t_4YclrGqM

During Who Framed Roger Rabbit on the NES, In the "Ink & Paint Club", you can find Jessica Rabbit's phone number which is an actual real-world number to call. Players could dial the number which would then have a recorded message set-up by LJN providing hints for the game. However, calling the number now will direct you to a phone-sex hotline.

According to developer Gregg Mayles, Banjo-Kazooie: Nuts and Bolts was actually the third attempt at creating 'Banjo-Threeie', the third installment in the main line of the franchise. The first attempt was supposedly BanjoX, an unfinished build for the original Xbox which featured some new assets and items. The second attempt, was a re-make of Banjo-Kazooie with some twists, and would have possibly featured Gruntilda following the duo around different worlds and trying to outdo them.

Out of all the games featured in Rare Replay, Grabbed by The Ghoulies was the only one to be remastered to run natively on the Xbox One, while other games received only bug fixes and minor adjustments to their controls.

According to former Rareware employee Chris Seavor, when the company was purchased by Microsoft, a number of the Microsoft executives thought that they had the rights to Donkey Kong until Rare corrected them.

When Microsoft had acquired Rare, they'd decided to keep their in-house Game Boy team as Microsoft had no intentions of entering the handheld market. Rare would continue to develop games for the Game Boy Advance and Nintendo DS. Microsoft themselves had also released other games on rival platforrms.

According to Chris Seavor (creator of Conker's Bad Fur Day), Rare wanted to explore 'amiibo styled things' way back during the days of the Nintendo 64. Rare even made figures of two of their characters for an unproduced fantasy video game called Urchin. The idea went nowhere with Rare and Nintendo at the time. Later, Nintendo decided to introduce the concept of Amiibos for the Nintendo Wii U and 3DS on June 10, 2014.

When first being developed, Oddworld: Abe's Exoddus had the working title of "Abe Gets Boned and Brewed".

In Abe's Oddysee, the race of the Mudokons had 4 fingers, however, in the Japanese release of Abe's Oddysee, and all releases of Abe's Exodus, the Mudokons only have 3 fingers. This is because Japanese see four fingers as an insult to the "meat packing sub class" of the past and is similar to the Jews wearing gold stars during World War II. Oddworld Inhabitants saw it as extortion and removed the 4 fingered design in every subsequent release of the series.

Munch's Oddysee was originally going to be released for the PlayStation 2, with different level layouts, enemies, cutscenes, and areas, but was scrapped and put on the Xbox. The idea to move the game to Xbox was based on the development team not only wanting to use a more powerful console, which would allow them to flesh out the world better, but also thinking it would be a better long term plan to publish the games on the console. Microsoft even worked with Oddworld Inhabitants to help make the Xbox better for them to work on it.

Stranger's Wrath creator Lorne Lanning has said that EA sabotaged the game by not marketing it.

The European version of Ape Escape disables controller input on the main menu if it detects itself to be a copy. The player may only skip the intro and view the title screen. The downside of this is that it prevents the European version from being played on a PlayStation 2 or 3 due to the software emulation setting off this measure.

The English voice acting for Ape Escape 2 was provided by voice actors from 4Kids Entertainment, the company who provided the English dub of Pokemon and Yu-Gi-Oh. Jimmy and Pink Monkey are voiced by Veronica Taylor, who provided the voice of Ash, Ash's mom, and May from Pokemon. Natalie is voiced by Rachel Lillis, who provided the voice of Misty, Jesse, and Jigglypuff in Pokemon. The professor and Spike are voiced by Dan Green, who voiced both young Yugi and adult Yugi in Yu-Gi-Oh. Specter, Blue Monkey, and Red Monkey are voiced by Greg Abbey, who provided the voice of Tristan in Yu-Gi-Oh.

In Ape Escape 3, After completing the game once, it's possible to purchase a mini-game called "Mesal Gear Solid" at the hobby shop, a parody of Metal Gear Solid.

Dart from Legend of Dragoon and Abe from Oddworld were both originally planned to be released as DLC characters for PlayStation All-Stars Battle Royale, but were ultimately cancelled. Concept art was made for Dart, and Abe was announced as cancelled DLC for April and May. Alongside the new characters, there were plans for a Gravity Rush/Journey stage, but it was also cancelled.

PaRappa's intro and ending for PlayStation All-Stars Battle Royale were made by the same company who did the PaRappa the Rapper anime.

Wipeout (1995) gained a significant amount of controversy with its promotional poster, which featured a bloody faced DJ Sara Cox. This was suspected by many to be depicting a drug overdose, as the game was considered part of the clubbing culture of the UK, which included a lot of illegal drug abuse, such as with ecstasy. Many politicians believed that the large "E" in the WipEout logo was in fact a reference to this culture.

There is a bug in Wipeout Pure where the "Triakis" craft's parameter controlling the rate of deceleration is slower than any other craft despite Triakis' weight. This was referenced in WipEout Pulse as the "reverse inertia destabilizer (RID) system", which led to Triakis being disqualified from the 2206 FX300 Championship.

Doctor Who: The Eternity Clock was originally intended to be part of a trilogy, however the sequels were later canceled. It's speculated that they were shelved due to the bugs present in the game at launch, and it receiving average review scores. The BBC has said that a sequel could still be made in the future, but did not have anything planned at the time.

Worms Armageddon had two versions of the Wormsong included in the game. The main version, Wormsong '99, can be heard in the main menu playing in the background. The second version can be heard when viewing the statistics screen after a battle and letting the background music roll, but only in the PC version. This version has somewhat different lyrics spoken in a Scottish accent, similar to the Angry Scots soundbank available for the worms.

The music of Crash Twinsanity was composed by an a capella group called Spiralmouth. This means that none of the soundtrack uses instruments, and was composed entirely with the human voice.

Virgin Interactive made and showed off a game for the Nintendo 64 called "Freak Boy." The game was made using the same SGI systems that was used to make the Nintendo 64 possible. According to press coverage, players would've been able to modify their heroes bodies, thereby helping solve puzzles. The game was cancelled after developers were asked to remake the game from scratch 2 times.

Microsoft DirectX was created in response to the PC port of The Lion King. The Lion King was released on Christmas 1994, and many children tried playing the game, but it would crash when loading. A Wall Street Journal article was published about someone spending his entire Christmas evening trying to get The Lion King to work for his daughter. Even Disney's helplines were flooded with phone calls. Many developers became suspicious of Windows as a viable platform, and stuck with MS-DOS. In response, Microsoft quickly developed the first version of DirectX for the upcoming Windows 95.

**Comment by rabbids4eva** [comment] 2018-10-22 14:56
Microsoft DirectX was created in response to the PC port of The Lion King. The Lion King was released on Christmas 1994, and many children tried playing the game, but it would crash when loading. A Wall Street Journal article was published about someone spending his entire Christmas evening trying to get The Lion King to work for his daughter. Even Disney's helplines were flooded with phone calls. Many developers became suspicious of Windows as a viable platform, and stuck with MS-DOS. In response, Microsoft quickly developed the first version of DirectX for the upcoming Windows 95.

**Comment by rabbids4eva** [comment] 2018-10-22 19:37
Parasite Eve included a 1998 Collector’s CD which includes previews of Xenogears, Bushido Blade 2, Brave Fencer Musashi, and Final Fantasy VIII.

Casper (1996) is an oddball release, coming out almost a year and a half after the movie was in theaters. Usually game releases are timed with the movie’s initial launch.

Twisted Metal (1995) is only one of 8 possible Long Box-era PlayStation games that are a single variant away from the “Perfect Five” variant set. That is, one of all three long boxes, jewel case, and Greatest Hits. So far it is believed that there is no “long box jewel / Saturn style” case variant, though. Only one turned up, and it was confirmed fake / assembled of other long box parts.

Assault Rigs was one of the few games that support the PlayStation Link Cable.

The packaging wasn’t lying – Descent Maximum was the last PlayStation Descent ever, not to mention the last console version. All future sequels were strictly PC.

Devil Disc started out as a Japanese fan program created on the Net Yaroze platform, which then got picked up for retail publishing.

The Greatest Hits version of Jet Moto 2 is actually a re-mastered “Championship Edition” version of the game that featured less racers but higher resolution graphics and other changes. Never meant to be published, internet lore says a dev team member ‘accidentally’ sent the CE version to Sony for Greatest Hits mastering.

Jumping Flash’s oddball character Muu became a somewhat celebrity of sorts. They even had their own PocketStation game.

Total Eclipse Turbo was released 10 days before the PlayStation system launch, making it the first game, first shooter, first port, and first “Kids to Adult” game released for it.

Gex: Enter The Gecko was known in Japan as "Spin Tail"

**Comment by rabbids4eva** [comment] 2018-10-27 00:05
At the height of Myst's popularity, a little known developer Parroty Games, who developed X-Fools, Star Warped and Microshaft Winblows 98, made "Pyst," a parody of the game they tried to cash in. Unsurprisingly, like their other "games," Pyst was harshly panned by critics.

Gizmondo, made by Tiger Telemantics, was often considered the worst-selling handheld system of all time, selling fewer than 25,000 units througout its one year lifespan.

Despite the poor reviews, sales, and having its rear end handed to by Nintendo's Game Boy Advance, the Nokia N-Gage was ahead of its time with the concept. Playing games on the phones (e.g. Angry Birds, Clash of Clans, Fallout Shelter) are a common thing nowadays, but back in 2003, when the N-Gage came out, was unheard of at the time.

Believe it or not, the original Alone in the Dark was made with a budget of US $400,000!

A PC version of the infamous 3DO game, Plumbers Don't Wear Ties, was reviewed by some magazines, including PC Gamer UK (3%), but it never surfaced. In 2017 the YouTube user psychoticgiraffe found a copy of the Windows 3.1 version in a library (Indiana) and released it online. It has the copyright year 1993, higher audio quality and does not include the video introduction by Jane.

The original release of the 3DO version of The Horde contained a bug that erased all other save data on the hard drive when a Horde game was saved. Crystal Dynamics offered to exchange the discs when users mailed in their defective copies.

Toys For Bob, the developers behind The Horde, almost ended up killing one of the game's actors (for real). In one FMV scene, the actor who plays the High Chancellor was supposed to eat a metal key (to reveal he wasn't really human). In order to do this a prop key was constructed out of chocolate sprinkled with cinnamon. Just as the actor was about to bit into the "key" he realized the prop men had made it out of chocolate, which it turns out he was fatally allergic to. The scene was later shot using a key made of carob instead.

Theme Park was originally going to be a Disney Land game but that was scrapped when they decided they would lose too much control over the development of the game's content.

Zool was the very first Amiga game to feature heavy product placement. Liberally spread throughout the levels (and even more so in the AGA release) were Chupa Chups lollipops and logos (designed by Salvador Dali, no less)...

The overall budget for The 7th Guest was more than one million dollars (a lot for a game on that times) and it was the first game on the history that comes with 2 CD-ROMs. Also one of the first ones on CD-ROM format at all.

Pitfall: The Mayan Adventure utilized the initial release of DirectX and was one of the first PC games to be released as a native Windows 95 executable.

At the time of its release, the music to Tempest 2000 was so popular, that gamers could purchase the CD soundtrack directly from Atari.

In Midway Arcade Treasures 3, the conversions of Hydro Thunder, Off Road Thunder, and San Francisco Rush were handled by China-based developer Gamestar. San Francisco Rush 2049 and Hydro Thunder are based on the Dreamcast versions, rather than the arcade originals. The other games in this collection are run in emulators written by Digital Eclipse.

Rayman Arena was originally going to be sold worldwide as Rayman M, until Ubi Soft realized that M usually stands for "Mature", so they changed the title for some regions.

If you examine the front cover of the U.S. Playstation cover for 40 Winks, you will notice a quote from an issue of Nintendo Official Magazine that says "Move Over Mario...". The reason for this somewhat humorous blurb is that a N64 version of 40 Winks was planned to be released, but eventually was canceled. But before the N64 version of the game got canceled, it was reviewed by Nintendo Official Magazine, which then resulted in a Playstation exclusive game using a Nintendo quote to downplay a Nintendo character.

One of the racers featured in LEGO Racers is Baron von Baron. He later returned in LEGO Racers 2 and LEGO Island 2, but was named "Sam Sanister" in the former and "Mr. Hates" in the latter.

Originally, during the early development of Rayman 2: The Great Escape, it was going to be a 2D side-scroller. However, because of the new and constant usage of 3D graphics in games of that era, the original 2D design was scrapped and Ubisoft decided to make their franchise 3D as well. Details and screenshots of the original prototype can be seen here. https://www.unseen64.net/2008/04/11/rayman2-2d-cancelled/

In the UK, some moral guardians were shocked by Alone In The Dark 2's content. Detective Chief Superintendent Mick Burdis from South Yorkshire CID called for the game to be banned from sale to children, saying, "It's sick. It can terrify them, damage their thought processes and make them insecure for life." Prompted by this, the Sheffield Star newspaper ran the headline, "Ban Kids From This Computer Sickness".

The music video that plays at the end of MDK is from the song "Non, Non, Rien N'a Changé" by the French band Billy Ze Kick and whom the development team are apparently fans of (they even urge you to buy their CD's on the readme file... good luck finding any!). The song appeared on the band's 1996 album Paniac and was released as a single in 1997.

The PlayStation version of MDK can be seen played during the very first scene of an episode of the science fiction series The X-Files. Series 5 episode 9 "Schizogeny" starts with a full close up of the games running, and then it pans across to the main character of the story who is playing it.

Oddworld Inhabitants made a TV commercial for Abe's Oddysee called "Guardian Angel", which features the shrink, a strange spider-like robot that warns Abe about his oncoming adventures. Eventually, this commercial got cancelled because it could scare children. Rumors say that the shrink was originally supposed to be a boss in the game but it was "cut out". According to Oddworld Inhabitants, shrinks are robots, whose purpose is to keep the captive Mudokon mother happy in order to produce eggs for the industrialists. Shrinks were also supposed to appear in Oddworld: Munch's Oddysee, but they were left out.

Worms Armageddon was at first intended to be an add-on for Worms 2, but there was so much new content that in 1998 Team 17 decided they would make it as a stand-alone game and improved the engine.

**Comment by rabbids4eva** [comment] 2020-11-01 14:42
Hi-Octane (PS1, Saturn) was rumored to begin life as something several Bullfrog programmers coded in free time, and then decided to improve the game and market it under the auspices of Electronic Arts. Peter Molyneux stated that EA set Bullfrog under pressure to release Dungeon Keeper, but they weren't able to do so within their deadlines. In order to relieve some of the pressure, they quickly developed Hi-Octane.

The final PS1 game ever made was Moorhuhn X, released exclusively in Europe on July 20th, 2005.

**Comment by rabbids4eva** [comment] 2022-05-11 20:17
Contrary to popular belief, PSExtreme is a real magazine, and it did actually give the game a 93%, along with their "Gold X Award" as an approval to play the game [(and is even listed on the EXcavate rating list from PSExtreme)](https://web.archive.org/web/19970601104334/http://www.psextreme.com/ratings.htm#GOLD). However, due to the unpopularity of the magazine in general, a mistaken rumor suggested that the magazine and the award were fake, and Accolade simply used them as a way to promote the game.

**Closed as completed** 2022-10-16 15:44 UTC
